import React, { useState } from 'react';
import { Language, Category, ImageStyle } from './types';
import { CATEGORIES, LANGUAGES } from './constants';
import LanguageSelector from './components/LanguageSelector';
import CategoryGrid from './components/CategoryGrid';
import FlashcardView from './components/FlashcardView';

const App: React.FC = () => {
  // Find English and set it as the default, otherwise fallback to the first language.
  const englishLanguage = LANGUAGES.find(lang => lang.code === 'en');
  const initialLanguages = englishLanguage ? [englishLanguage] : [LANGUAGES[0]];
  const [selectedLanguages, setSelectedLanguages] = useState<Language[]>(initialLanguages);
  const [currentCategory, setCurrentCategory] = useState<Category | null>(null);
  const [selectedImageStyle, setSelectedImageStyle] = useState<ImageStyle>('illustration');

  const handleLanguageChange = (language: Language) => {
    setSelectedLanguages(prev => {
      const isSelected = prev.some(l => l.code === language.code);
      if (isSelected) {
        // Prevent deselecting the last language
        if (prev.length === 1) {
          return prev;
        }
        return prev.filter(l => l.code !== language.code);
      } else {
        // Prevent selecting more than 3 languages
        if (prev.length >= 3) {
          return prev;
        }
        return [...prev, language];
      }
    });
  };

  const handleSelectCategory = (category: Category, style: ImageStyle) => {
    setCurrentCategory(category);
    setSelectedImageStyle(style);
  };

  const handleBackToCategories = () => {
    setCurrentCategory(null);
  };

  return (
    <div className="min-h-screen bg-sky-50 text-slate-800 font-sans p-4 sm:p-6 md:p-8 flex flex-col items-center">
      <div className="w-full max-w-4xl mx-auto">
        <header className="text-center mb-8">
          <h1 className="text-4xl sm:text-5xl font-bold text-sky-600">Baby's First Words</h1>
          <p className="text-slate-500 mt-2 text-lg">Multilingual Flashcards for Little Learners</p>
        </header>

        <main>
          {currentCategory ? (
            <FlashcardView
              category={currentCategory}
              selectedLanguages={selectedLanguages}
              onBack={handleBackToCategories}
              imageStyle={selectedImageStyle}
            />
          ) : (
            <>
              <LanguageSelector
                availableLanguages={LANGUAGES}
                selectedLanguages={selectedLanguages}
                onLanguageChange={handleLanguageChange}
              />
              <CategoryGrid
                categories={CATEGORIES}
                onSelectCategory={handleSelectCategory}
              />
            </>
          )}
        </main>
        
        <footer className="text-center mt-12 text-slate-400 text-sm">
          <p>Powered by Gemini. Images generated by AI.</p>
        </footer>
      </div>
    </div>
  );
};

export default App;